# Lab 01 hints : numpy


[Numpy cheat sheet](https://res.cloudinary.com/dyd911kmh/image/upload/v1676302459/Marketing/Blog/Numpy_Cheat_Sheet.pdf)

In [3]:
import numpy as np

# Saving / Loading text file :

In [ ]:
# Load a txt file :
a = np.loadtxt('path_to_in_file.txt', delimiter=',')

# The delimiter needs to be adapted to your txt file, usualy spaces, tab, comma or semicolon
# other options such as skiping first rows, loading only certain columns, are available (see doc.)

# Save a txt file :
np.savetxt('path_to_out_file.txt', a, delimiter=',')

# Access on 2D np arrays

In [4]:
a = np.array([[1,2,3], [4,5,6]])

#Get array shape :
print(a.shape)

# Accessing an element at line i column j :
i = 0
j = 0

x = a[i,j]

#Extract line i : 
# : operator means all elements along the specified dimension
i = 0
l = a[i,:] #Extract elements of line i along all columns

# Extract column i : 
c = a[:,i]

#Iterate over all lines of a 2D array:
for i in range(a.shape[0]):
    li = a[i,:]
    
#Iterate over all columns of a 2D array:
for j in range(a.shape[1]):
    cj = a[i,:]
    
    

(2, 3)


# Operations on 2D np arrrays

### Element wise operation on arrays :
Using an operator followed by a constant value will perform an elementwise operation,
i.e. the operation will be applied independently to each element of the array

In [5]:
b = a + 5

print(b)
# This adds 5 to each element of the array. Same holds for many operators, +, -, *, /, //, %, **, ...

[[ 6  7  8]
 [ 9 10 11]]


### Example : 

Estimating perspective coordinates from top left coordinates (both xy and uv are Nx2 np.array)
   
To estimate all x at once from u, one can extract u from uv (column 0), then apply the sequence of element wise operations to finally fill the x column (i.e. column 0 -> xy[:,0])


In [ ]:
xy[:,0] = (uv[:,0] - (.5*(w-1) + cx))/c

### Array to array operations :

Array of the same shape :
Using an operator between two arrays will apply the operator element to element between the two arrays.

In [32]:
c = np.ones((a.shape))

d = a + c
print(d)

[[2. 3. 4.]
 [5. 6. 7.]]


Array of broadcastable shape :
Imagine having an array of two columns such as uv. You might want to apply one operation to all u's and another one to all v's. To do so, you can apply all operations at once by building an array of operations :

In [34]:
# Subtract 1 to all element of the first column of a and subtract 2 on the second column
print(a_shape)

e = a - np.array([[1],[2]])

print(e)

# Subtract 1 to the first line of the array, 2 to the second and 3 to the third 
f = a - np.array([[1, 2, 3]])

print(f)

(2, 3)
[[0 1 2]
 [2 3 4]]
[[0 0 0]
 [3 3 3]]


# Notes on scipy.optimize.fsolve

fsolve is a non linear solver that proves usefull when trying to solve non linear system of equations with an initial guess, such as undistortion equations.

It can be called as follow :  
sol = scipy.optimize.fsolve(undistort, x0, args=())  

1. The system of equations you try to solve is implemented as a function, defined by **undistort**  
2. The variables that fsolve tries to find is the first (and only the first) argument of the **undistort** function. This explains why you need to pack x,y variables into a vector that is provided to **undistort** as first argument.
3. x0 is the initial guess that fsolve will use. Since you want to solve for a vector of arguments (x and y), you can build a vector with the raw (i.e. distorted) x and y value that will be used as initial guess.
4. args are all other arguments that the function takes. In our case x distorted and y distorted (although you already provided them as initial guess, they are still needed as constants in the equation (1) and (2)), k1, k2, p1, p2

In practice, the fsolve function will be called N times (N being your number of measurements), solving the system for one measurement at a time.